openapi: 3.0.0
info:
  title: Pocki Chatbot 
  description: Documentación de la API del chatbot con Express y MySQL
  version: 1.0.0

servers:
  - url: http://localhost:3001

paths:
  /messages/crearMensaje:
    post:
      summary: Enviar mensaje y obtener respuesta del bot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        '201':
          description: Mensaje guardado y respuesta del bot enviada
        '400':
          description: Faltan campos requeridos
        '500':
          description: Error interno del servidor

  /messages/obtenerMensajes:
    get:
      summary: Obtener todos los mensajes registrados
      responses:
        '200':
          description: Lista de mensajes
        '404':
          description: No se encontraron mensajes
        '500':
          description: Error al obtener los mensajes
